- group: {name: future, enabled: true}
- group: {name: generalise, enabled: true}
- functions:
  - {name: undefined, within: []}
# Do not prohibit using more monomorphic functions
- ignore: {name: Use pure}
- ignore: {name: Use fmap}
- ignore: {name: Use traverse_}
- ignore: {name: "Use <>"}
# Do not enforce less explicit expressions
# and util functions consisting of single line of code
- ignore: {name: Use isNothing}
- ignore: {name: Use print}
- ignore: {name: Use null}
- ignore: {name: Use notElem}
- ignore: {name: Use unless}
- ignore: {name: "Use asks"}
- ignore: {name: "Eta reduce"}
