name: Haskell-CI
on:
  - push
  - pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache DevX
      uses: actions/cache@v3
      with:
        path: /nix
        key: "devx-ghc96"
    - name: Setup DevX
      uses: input-output-hk/actions/devx@latest
      with:
        platform: 'x86_64-linux'
        compiler-nix-name: 'ghc96'
        minimal: false
        iog: true
    - name: Check Nix env
      shell: devx {0}
      run: |
        echo 'Running in DevX'
        ghc --version
        cabal --version
    - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-
    - name: Cabal build and test
      shell: devx {0}
      run: |
        cabal update
        cabal build
        cabal test
    - name: Install and run linters
      shell: devx {0}
      run: |
        cabal install cabal-fmt
        cabal install fourmolu
        /home/runner/.cabal-devx/bin/cabal-fmt --check cem-script.cabal
        /home/runner/.cabal-devx/bin/fourmolu .
